# Utiliser l'image officielle Node.js comme image de base
FROM node:18

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier package.json et package-lock.json dans le répertoire de travail
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste de l'application dans le répertoire de travail
COPY . .

# Exposer le port sur lequel l'application sera accessible
EXPOSE 3000

# Commande pour lancer l'application en mode développement
CMD ["npm", "start"]